### ISSUE TITLE
isChecksumAddress TypeError

### ISSUE THREAD

**Issue by wildfunctions** [cilphex/ethereum-address#4]
Looks like the isChecksumAddress function is throwing following error for values 'a', '0xa', etc.

```
    TypeError: Cannot read property 'toUpperCase' of undefined

      92 |     isEthereumAddressValid(validationAddress) {
      93 |       console.log(`What is going on with ${validationAddress}`);
    > 94 |       return this.ethereum.isChecksumAddress(validationAddress);
      95 |     }
      96 | 
      97 |     processAndValidateEthereum(addressObj, coin, component) {
      
      at Object.isChecksumAddress (node_modules/ethereum-address/index.js:33:61)
      at CoinValidation.isEthereumAddressValid (utils/coinvalidation.js:94:22)
      at Object.<anonymous> (__tests__/coinvalidation.test.js:77:19)
```

**Comment by liukun** [comment]
You need to use `isAddress` which includes `isChecksumAddress`.
